# Generated by Django 5.2.10 on 2026-02-27 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0015_alter_event_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FrenchHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("year", models.IntegerField(verbose_name="Année")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Jour férié",
                "verbose_name_plural": "Jours fériés",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveCalendar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du calendrier"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "visibility_end_date",
                    models.DateField(
                        help_text="Le calendrier reste visible jusqu'à cette date",
                        verbose_name="Date de fin de visibilité",
                    ),
                ),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False, verbose_name="Notification envoyée"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendars_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "sectors",
                    models.ManyToManyField(
                        related_name="leave_calendars",
                        to="events.sector",
                        verbose_name="Secteurs concernés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendrier de congés",
                "verbose_name_plural": "Calendriers de congés",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("full", "Journée entière"),
                            ("morning", "Matin"),
                            ("afternoon", "Après-midi"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="Période",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="leave.leavecalendar",
                        verbose_name="Calendrier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de congés",
                "verbose_name_plural": "Demandes de congés",
                "ordering": ["date", "period"],
                "unique_together": {("calendar", "user", "date", "period")},
            },
        ),
        migrations.CreateModel(
            name="LeaveHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Créé"),
                            ("updated", "Modifié"),
                            ("deleted", "Supprimé"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "old_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Anciennes données"
                    ),
                ),
                (
                    "new_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Nouvelles données"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="leave.leaverequest",
                        verbose_name="Demande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de modification",
                "verbose_name_plural": "Historiques de modifications",
                "ordering": ["-timestamp"],
            },
        ),
    ]
