# Generated by Django 5.2.10 on 2026-02-27 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavehistory",
            name="leave_request_info",
            field=models.JSONField(
                blank=True,
                help_text="Stocké pour les suppressions quand la demande n'existe plus",
                null=True,
                verbose_name="Infos de la demande",
            ),
        ),
        migrations.AlterField(
            model_name="leavehistory",
            name="leave_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="history",
                to="leave.leaverequest",
                verbose_name="Demande",
            ),
        ),
    ]
