# Generated by Django 5.2.10 on 2026-02-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="sector",
        ),
        migrations.AddField(
            model_name="event",
            name="sectors",
            field=models.ManyToManyField(
                related_name="events", to="events.sector", verbose_name="Secteurs"
            ),
        ),
    ]
