# Generated by Django 5.2.10 on 2026-02-05 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_event_sector_event_sectors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="notify_on_publish",
            field=models.BooleanField(
                default=False,
                verbose_name="Recevoir un email lors de la confirmation de la publication",
            ),
        ),
        migrations.CreateModel(
            name="EventValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(default=False, verbose_name="Validé par la communication"),
                ),
                (
                    "validated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Validé le"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes de validation"),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation d'événement",
                "verbose_name_plural": "Validations d'événements",
                "ordering": ["-validated_at"],
            },
        ),
    ]
