# Generated by Django 5.2.10 on 2026-02-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_notify_on_publish_eventvalidation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="Optionnel - laissez vide si l'événement n'a pas de date de fin définie",
                null=True,
                verbose_name="Date et heure de fin",
            ),
        ),
    ]
