# Generated by Django 5.2.10 on 2026-02-05 15:21

import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_make_end_datetime_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "document",
                    models.FileField(
                        help_text="Formats acceptés : PDF, Word (doc/docx), Excel (xls/xlsx). Taille max : 20 Mo",
                        upload_to="events/documents/%Y/%m/",
                        verbose_name="Document",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pdf", "PDF"),
                            ("word", "Word"),
                            ("excel", "Excel"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploadé le"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Taille (octets)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Document d'événement",
                "verbose_name_plural": "Documents d'événements",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EventOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Occurrence d'événement",
                "verbose_name_plural": "Occurrences d'événements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventRecurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("daily", "Quotidien"),
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuel"),
                            ("yearly", "Annuel"),
                        ],
                        default="weekly",
                        max_length=20,
                        verbose_name="Type de récurrence",
                    ),
                ),
                (
                    "interval",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Tous les X jours/semaines/mois/années",
                        verbose_name="Intervalle",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Laissez vide pour une récurrence sans fin",
                        null=True,
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "days_of_week",
                    models.CharField(
                        blank=True,
                        help_text="Pour la récurrence hebdomadaire : 0,1,2 pour Lundi,Mardi,Mercredi",
                        max_length=20,
                        verbose_name="Jours de la semaine",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Pour la récurrence mensuelle (1-31)",
                        null=True,
                        verbose_name="Jour du mois",
                    ),
                ),
                (
                    "month_of_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Pour la récurrence annuelle (1-12)",
                        null=True,
                        verbose_name="Mois de l'année",
                    ),
                ),
                (
                    "max_occurrences",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Laissez vide pour illimité",
                        null=True,
                        verbose_name="Nombre maximum d'occurrences",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Récurrence d'événement",
                "verbose_name_plural": "Récurrences d'événements",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["search_vector"], name="events_even_search__5d42c6_idx"),
        ),
        migrations.AddField(
            model_name="eventdocument",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="events.event",
                verbose_name="Événement",
            ),
        ),
        migrations.AddField(
            model_name="eventdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uploadé par",
            ),
        ),
        migrations.AddField(
            model_name="eventoccurrence",
            name="occurrence",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_occurrence",
                to="events.event",
                verbose_name="Occurrence",
            ),
        ),
        migrations.AddField(
            model_name="eventoccurrence",
            name="parent_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrences",
                to="events.event",
                verbose_name="Événement parent",
            ),
        ),
        migrations.AddField(
            model_name="eventrecurrence",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurrence",
                to="events.event",
                verbose_name="Événement parent",
            ),
        ),
    ]
