# Generated by Django 5.2.10 on 2026-02-06 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_eventdocument_eventoccurrence_eventrecurrence_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Adresse email qui recevra les demandes de tournage vidéo",
                        max_length=254,
                        verbose_name="Email de notification",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre de notification vidéo",
                "verbose_name_plural": "Paramètres de notification vidéo",
            },
        ),
        migrations.CreateModel(
            name="VideoRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Envoyé le"),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="Email destinataire"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Envoyé"), ("failed", "Échec")],
                        default="sent",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_requests",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_video_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Envoyé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de tournage vidéo",
                "verbose_name_plural": "Demandes de tournage vidéo",
                "ordering": ["-sent_at"],
            },
        ),
    ]
