# Generated by Django 5.2.10 on 2026-02-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_videonotificationsettings_videorequestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="videorequestlog",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Commentaire optionnel pour la demande de tournage (max 500 caractères)",
                max_length=500,
                null=True,
                verbose_name="Commentaire",
            ),
        ),
    ]
