# Generated by Django 5.2.10 on 2026-02-06 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_add_video_request_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="videorequestlog",
            name="confirmation_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="Token de confirmation"
            ),
        ),
        migrations.AddField(
            model_name="videorequestlog",
            name="confirmed",
            field=models.BooleanField(default=False, verbose_name="Validé par le caméraman"),
        ),
        migrations.AddField(
            model_name="videorequestlog",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de validation"),
        ),
    ]
