# Generated by Django 5.2.10 on 2026-02-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_add_video_request_confirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="videorequestlog",
            name="refused",
            field=models.BooleanField(default=False, verbose_name="Refuse par le cameraman"),
        ),
        migrations.AddField(
            model_name="videorequestlog",
            name="refused_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de refus"),
        ),
    ]
