# Generated by Django 5.2.10 on 2026-02-23 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_remove_email_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsettings",
            name="default_from_email",
            field=models.EmailField(
                default="j.brechoire@cc-sudavesnois.fr",
                help_text="Adresse email utilisée pour envoyer les notifications",
                max_length=254,
                verbose_name="Email d'expédition",
            ),
        ),
        migrations.AlterField(
            model_name="eventsettings",
            name="video_notification_email",
            field=models.EmailField(
                default="j.brechoire@cc-sudavesnois.fr",
                help_text="Adresse email qui recevra les demandes de tournage vidéo",
                max_length=254,
                verbose_name="Email de notification vidéo",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["end_datetime"], name="events_even_end_dat_53a75f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_active", "start_datetime", "end_datetime"],
                name="events_even_is_acti_6ca192_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventcomment",
            index=models.Index(
                fields=["event", "-created_at"], name="events_even_event_i_ba55cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventcomment",
            index=models.Index(
                fields=["author", "-created_at"], name="events_even_author__073443_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventvalidation",
            index=models.Index(
                fields=["is_validated"], name="events_even_is_vali_40e147_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventvalidation",
            index=models.Index(
                fields=["event", "is_validated"], name="events_even_event_i_d7361d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventvalidation",
            index=models.Index(
                fields=["validated_at"], name="events_even_validat_cf9b22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videorequestlog",
            index=models.Index(
                fields=["event", "-sent_at"], name="events_vide_event_i_c37af0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videorequestlog",
            index=models.Index(
                fields=["confirmation_token"], name="events_vide_confirm_cb1ea2_idx"
            ),
        ),
    ]
