# Generated by Django 5.2.10 on 2026-02-23 16:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom de la section",
                        max_length=100,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description optionnelle de la section",
                        verbose_name="Description",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#64748b",
                        help_text="Code couleur HEX (ex: #3b82f6)",
                        max_length=7,
                        verbose_name="Couleur",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Désactiver pour masquer la section",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Ordre d'affichage", verbose_name="Ordre"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Type de section",
                "verbose_name_plural": "Types de section",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DailyTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date du pointage", verbose_name="Date"),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre de visites/appels",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Compteur",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_trackings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_trackings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trackings",
                        to="pointage.sectiontype",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pointage journalier",
                "verbose_name_plural": "Pointages journaliers",
                "ordering": ["-date", "section__order"],
            },
        ),
        migrations.CreateModel(
            name="TrackingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_count",
                    models.IntegerField(
                        help_text="Valeur avant modification",
                        verbose_name="Ancien compteur",
                    ),
                ),
                (
                    "new_count",
                    models.IntegerField(
                        help_text="Valeur après modification",
                        verbose_name="Nouveau compteur",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date de modification"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Raison de la modification (optionnel)",
                        max_length=255,
                        verbose_name="Raison",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "tracking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="pointage.dailytracking",
                        verbose_name="Pointage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de modification",
                "verbose_name_plural": "Historiques de modifications",
                "ordering": ["-modified_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dailytracking",
            index=models.Index(fields=["date", "section"], name="pointage_da_date_e2c85f_idx"),
        ),
        migrations.AddIndex(
            model_name="dailytracking",
            index=models.Index(fields=["date"], name="pointage_da_date_7da292_idx"),
        ),
        migrations.AddIndex(
            model_name="dailytracking",
            index=models.Index(fields=["section"], name="pointage_da_section_c07141_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailytracking",
            unique_together={("date", "section")},
        ),
    ]
