# Generated by Django 5.2.10 on 2026-02-25 08:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notify_on_new_ticket",
                    models.BooleanField(default=True, verbose_name="Notifier sur nouveau ticket"),
                ),
                (
                    "notify_on_status_change",
                    models.BooleanField(
                        default=True, verbose_name="Notifier sur changement de statut"
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email utilisé pour envoyer les notifications",
                        max_length=254,
                        verbose_name="Email d'expédition",
                    ),
                ),
                (
                    "email_recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="feedback_email_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataires des emails",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres de feedback",
                "verbose_name_plural": "Paramètres de feedback",
            },
        ),
        migrations.CreateModel(
            name="FeedbackTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("bug", "Bug"),
                            ("feature", "Amélioration"),
                            ("question", "Question"),
                        ],
                        default="bug",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyenne"),
                            ("high", "Haute"),
                            ("critical", "Critique"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("in_progress", "En cours"),
                            ("resolved", "Résolu"),
                            ("closed", "Fermé"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        help_text="Formats acceptés : JPG, PNG (max 2MB)",
                        null=True,
                        upload_to="feedback/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Capture d'écran",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigné à",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket de feedback",
                "verbose_name_plural": "Tickets de feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "is_staff_response",
                    models.BooleanField(default=False, verbose_name="Réponse du support"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="feedback.feedbackticket",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="feedbackticket",
            index=models.Index(
                fields=["status", "created_at"], name="feedback_fe_status_bcda79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackticket",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="feedback_fe_created_4a23e4_idx",
            ),
        ),
    ]
