# Generated by Django 5.2.10 on 2026-02-05 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="nom"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#EF4444", "Rouge"),
                            ("#F97316", "Orange"),
                            ("#F59E0B", "Jaune"),
                            ("#84CC16", "Vert lime"),
                            ("#10B981", "Vert"),
                            ("#06B6D4", "Cyan"),
                            ("#3B82F6", "Bleu"),
                            ("#6366F1", "Indigo"),
                            ("#8B5CF6", "Violet"),
                            ("#D946EF", "Fuchsia"),
                            ("#EC4899", "Rose"),
                            ("#6B7280", "Gris"),
                        ],
                        default="#3B82F6",
                        max_length=7,
                        verbose_name="couleur",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Attribut automatiquement aux nouveaux utilisateurs",
                        verbose_name="rôle par défaut",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "rôle",
                "verbose_name_plural": "rôles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PagePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(db_index=True, max_length=100, verbose_name="nom de l'app"),
                ),
                (
                    "view_name",
                    models.CharField(max_length=200, verbose_name="nom de la vue"),
                ),
                (
                    "url_name",
                    models.CharField(db_index=True, max_length=200, verbose_name="nom de l'URL"),
                ),
                (
                    "url_pattern",
                    models.CharField(max_length=500, verbose_name="pattern d'URL"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "codename",
                    models.CharField(
                        db_index=True,
                        max_length=300,
                        unique=True,
                        verbose_name="code unique",
                    ),
                ),
                (
                    "http_method",
                    models.CharField(
                        choices=[
                            ("GET", "Voir"),
                            ("POST", "Ajouter"),
                            ("PUT", "Modifier"),
                            ("DELETE", "Supprimer"),
                            ("PATCH", "Modifier partiellement"),
                        ],
                        default="GET",
                        max_length=10,
                        verbose_name="méthode HTTP",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "auto_detected",
                    models.BooleanField(default=True, verbose_name="détecté automatiquement"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "permission de page",
                "verbose_name_plural": "permissions de pages",
                "ordering": ["app_name", "view_name", "http_method"],
                "indexes": [
                    models.Index(
                        fields=["app_name", "is_active"],
                        name="accounts_pa_app_nam_822984_idx",
                    ),
                    models.Index(fields=["codename"], name="accounts_pa_codenam_f13395_idx"),
                ],
                "unique_together": {("app_name", "url_name", "http_method")},
            },
        ),
        migrations.CreateModel(
            name="PermissionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("UPDATE", "Modification"),
                            ("DELETE", "Suppression"),
                            ("ASSIGN", "Attribution"),
                            ("REVOKE", "Révocation"),
                        ],
                        max_length=10,
                        verbose_name="action",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="détails"),
                ),
                (
                    "performed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="effectué le"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="adresse IP"),
                ),
                (
                    "page_permission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.pagepermission",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur concerné",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "historique de permission",
                "verbose_name_plural": "historiques de permissions",
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-performed_at"],
                        name="accounts_pe_user_id_69fd5d_idx",
                    ),
                    models.Index(
                        fields=["action", "-performed_at"],
                        name="accounts_pe_action_a51f43_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RolePagePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_access",
                    models.BooleanField(default=False, verbose_name="peut accéder"),
                ),
                (
                    "can_add",
                    models.BooleanField(default=False, verbose_name="peut ajouter"),
                ),
                (
                    "can_change",
                    models.BooleanField(default=False, verbose_name="peut modifier"),
                ),
                (
                    "can_delete",
                    models.BooleanField(default=False, verbose_name="peut supprimer"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "page_permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="accounts.pagepermission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_permissions",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "permission de rôle",
                "verbose_name_plural": "permissions de rôles",
                "ordering": ["page_permission__app_name", "page_permission__view_name"],
                "unique_together": {("role", "page_permission")},
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="attribué le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_users",
                        to="accounts.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "rôle utilisateur",
                "verbose_name_plural": "rôles utilisateurs",
                "ordering": ["-assigned_at"],
                "unique_together": {("user", "role")},
            },
        ),
    ]
