# Generated by Django 5.2.10 on 2026-02-06 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_role_pagepermission_permissionhistory_and_more"),
        ("events", "0008_add_video_request_confirmation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("video_refused", "Refus de tournage vidéo"),
                            ("video_confirmed", "Confirmation de tournage vidéo"),
                            ("event_created", "Nouvel événement créé"),
                            ("event_updated", "Événement modifié"),
                            ("event_validated", "Événement validé"),
                            ("event_rejected", "Événement rejeté"),
                            ("video_request_sent", "Demande de tournage envoyée"),
                        ],
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                ("message", models.TextField(verbose_name="message")),
                ("is_read", models.BooleanField(default=False, verbose_name="lue")),
                ("link", models.URLField(blank=True, verbose_name="lien")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="events.event",
                        verbose_name="événement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
                (
                    "video_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="events.videorequestlog",
                        verbose_name="demande vidéo",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="accounts_no_user_id_b29cd4_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_no_user_id_b37b35_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="accounts_no_notific_681bde_idx",
                    ),
                ],
            },
        ),
    ]
