# Generated by Django 5.2.10 on 2026-02-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_user_notification_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("video_refused", "Refus de tournage vidéo"),
                    ("video_confirmed", "Confirmation de tournage vidéo"),
                    ("event_created", "Nouvel événement créé"),
                    ("event_updated", "Événement modifié"),
                    ("event_deleted", "Événement supprimé"),
                    ("event_commented", "Nouveau commentaire"),
                    ("event_validated", "Événement validé"),
                    ("event_rejected", "Événement rejeté"),
                    ("video_request_sent", "Demande de tournage envoyée"),
                    ("feedback_new_ticket", "Nouveau ticket de feedback"),
                    ("feedback_status_changed", "Statut de ticket modifié"),
                ],
                max_length=50,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("video_refused", "Refus de tournage vidéo"),
                    ("video_confirmed", "Confirmation de tournage vidéo"),
                    ("event_created", "Nouvel événement créé"),
                    ("event_updated", "Événement modifié"),
                    ("event_deleted", "Événement supprimé"),
                    ("event_commented", "Nouveau commentaire"),
                    ("event_validated", "Événement validé"),
                    ("event_rejected", "Événement rejeté"),
                    ("video_request_sent", "Demande de tournage envoyée"),
                    ("feedback_new_ticket", "Nouveau ticket de feedback"),
                    ("feedback_status_changed", "Statut de ticket modifié"),
                ],
                max_length=50,
                verbose_name="type de notification",
            ),
        ),
    ]
