# Generated by Django 5.2.10 on 2026-02-17 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Configuration principale", max_length=100),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("database", "Base de données uniquement"),
                            ("media", "Dossier média uniquement"),
                            ("full", "Base de données + Média"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="Type de sauvegarde",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Quotidien"),
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuel"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Fréquence",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "backup_directory",
                    models.CharField(
                        default="/home/noro8560/backup-gestionccsa",
                        max_length=255,
                        verbose_name="Dossier de sauvegarde",
                    ),
                ),
                (
                    "keep_last_n",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Conserver les N dernières sauvegardes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration de sauvegarde",
                "verbose_name_plural": "Configurations de sauvegarde",
            },
        ),
        migrations.CreateModel(
            name="BackupHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("database", "Base de données"),
                            ("media", "Dossier média"),
                            ("full", "Complète"),
                        ],
                        max_length=20,
                        verbose_name="Type de sauvegarde",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("manual", "Manuel"), ("automatic", "Automatique")],
                        default="manual",
                        max_length=20,
                        verbose_name="Déclencheur",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En cours"),
                            ("success", "Succès"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(blank=True, max_length=500, verbose_name="Chemin du fichier"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Taille du fichier (octets)"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Démarré à"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Terminé à"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de sauvegarde",
                "verbose_name_plural": "Historiques de sauvegarde",
                "ordering": ["-started_at"],
            },
        ),
    ]
