# Generated by Django 5.2.10 on 2026-02-20 10:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code unique pour l'URL courte (laissez vide pour génération automatique)",
                        max_length=20,
                        unique=True,
                        verbose_name="code court",
                    ),
                ),
                (
                    "original_url",
                    models.URLField(
                        help_text="L'URL externe à raccourcir",
                        max_length=2000,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="URL originale",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortened_urls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL raccourcie",
                "verbose_name_plural": "URLs raccourcies",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="url_shorten_code_9aea02_idx"),
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="url_shorten_created_27bc61_idx",
                    ),
                ],
            },
        ),
    ]
